### Find user's food diary
GET http://localhost:3333/api/personal-account/food-diary HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MDg2MjA4OCwiZXhwIjoxNjgwODYyOTg4fQ.TPfakzNz_upRv7jJCtGtEapvvrJn_dZoKZ-bmLoIDiY

### Find user's workout diary
GET http://localhost:3333/api/personal-account/workout-diary HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTEwMzUwMSwiZXhwIjoxNjgxMTA0NDAxfQ.YaHdAZYqU-7qquXct7CR9RzCH03vCu4s4rqxigJNl-k

### Save user's food diary
PATCH http://localhost:3333/api/personal-account/food-diary HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MDg2MjA4OCwiZXhwIjoxNjgwODYyOTg4fQ.TPfakzNz_upRv7jJCtGtEapvvrJn_dZoKZ-bmLoIDiY

{
  # сбор данных с таблицы через FormData API
  "calories": ["820", "", "620", "", "620", "", "620", "", "810", "", "810", "", "810", "810", "770", "", "770", "770", "", "770", "770", "390", "390", "", "390", "390", "", "390"]
}

### Save user's workout diary
PATCH http://localhost:3333/api/personal-account/workout-diary HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MDg2MjA4OCwiZXhwIjoxNjgwODYyOTg4fQ.TPfakzNz_upRv7jJCtGtEapvvrJn_dZoKZ-bmLoIDiY

{
  "workoutId": 4,
  "calory": "870",
  "trainingTime": "80",
  "date": "05.04.2023, thursday"
}

### Add a new favorite gym
POST http://localhost:3333/api/personal-account/favorite-gyms/18 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTAyMDk0MSwiZXhwIjoxNjgxMDIxODQxfQ.klVnF_xVrUuWYUbjXgfvgyyF5G7HJwCtEuEYoL8j3fI

### Find user's favorite gyms
GET http://localhost:3333/api/personal-account/favorite-gyms HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTEwMzUwMSwiZXhwIjoxNjgxMTA0NDAxfQ.YaHdAZYqU-7qquXct7CR9RzCH03vCu4s4rqxigJNl-k

### Remove a favorite gym
DELETE http://localhost:3333/api/personal-account/favorite-gyms/18 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTAyMDk0MSwiZXhwIjoxNjgxMDIxODQxfQ.klVnF_xVrUuWYUbjXgfvgyyF5G7HJwCtEuEYoL8j3fI

### Add a new workout purchase
POST http://localhost:3333/api/personal-account/my-purchases/workouts/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTExMDQ0NCwiZXhwIjoxNjgxMTExMzQ0fQ.eVkZ9IXRMCeUiptSl2T8Oe0OraJQD7iBiSEY0KFTpQg

### Remove a workout purchase
PATCH http://localhost:3333/api/personal-account/my-purchases/workouts/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTExMDQ0NCwiZXhwIjoxNjgxMTExMzQ0fQ.eVkZ9IXRMCeUiptSl2T8Oe0OraJQD7iBiSEY0KFTpQg

### Add a new gym purchase
POST http://localhost:3333/api/personal-account/my-purchases/gyms/17 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTExMjAxOSwiZXhwIjoxNjgxMTEyOTE5fQ.H5tAZpHg41TohdZI2UUrM8UogeqQcvRXIrWpB0KHbIA

### Remove a gym purchase
PATCH http://localhost:3333/api/personal-account/my-purchases/gyms/18 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTExMDQ0NCwiZXhwIjoxNjgxMTExMzQ0fQ.eVkZ9IXRMCeUiptSl2T8Oe0OraJQD7iBiSEY0KFTpQg

### Find user's purchases
GET http://localhost:3333/api/personal-account/my-purchases?limit=8&page=1&purchaseType=workouts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTEyNTg2OCwiZXhwIjoxNjgxMTI2NzY4fQ.L9r2PnonEJXBxgh9DBcdn8X5qnbtv4qDGedGP7-Es7Y
