### Create a new workout
POST http://localhost:3334/api/workouts/coach HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDI0MDg0YjcxZGZjMzY2ODM3ZWMiLCJlbWFpbCI6Im1lQGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoiSGF3ayBDaGlwIiwiaWF0IjoxNjgxNTY2ODA4LCJleHAiOjE2ODE1Njc3MDh9.kEeLQfMaw8jrGeiqbMFTkc2iymLjmhhSDXmpKlTFd94

{
  "title": "Amet dolore.",
  "experience": "любитель",
  "specialization": "пилатес",
  "trainingTime": "больше 80 мин",
  "cost": 1400,
  "calories": 2900,
  "description": "Nulla mollit consequat deserunt in ex.",
  "sex": "для всех",
  "isSpecialOffer": true
}

### Update existed workout
PATCH http://localhost:3334/api/workouts/coach/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDI0MDg0YjcxZGZjMzY2ODM3ZWMiLCJlbWFpbCI6Im1lQGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoiSGF3ayBDaGlwIiwiaWF0IjoxNjc5MzEyNTY3LCJleHAiOjE2NzkzMTM0Njd9.vIiZHwavCKwinMEX-YT6bKhPt2ciSYwm4BrVzd-zdlQ


{
  "title": "Amet dolore.",
  "specialization": "пилатес",
  "trainingTime": "50-80 мин",
  "cost": 1500,
  "calories": 2700,
  "description": "Nulla mollit consequat deserunt in ex.",
  "sex": "для мужчин",
  "isSpecialOffer": true
}

### Find existed workout
GET  http://localhost:3334/api/workouts/7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTczOTg2NiwiZXhwIjoxNjgxNzQwNzY2fQ.DBoJPXaBIV9Em_k9o0OSW5mwaRU9aiZYutAd7SzLLsM

### Find existed gym
GET  http://localhost:3334/api/workouts/gym/24 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTEwOTYxMiwiZXhwIjoxNjgxMTEwNTEyfQ.wsKhL8XwEqDde1IZ0wuh41LqJYJ20vYy-ca8GOwmOwg

### Find existed workouts
GET  http://localhost:3334/api/workouts?limit=2&sortDirection=asc&workoutIds=3,4&page=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTExOTgzNiwiZXhwIjoxNjgxMTIwNzM2fQ.8RhmZMOjwCQEgPKFu_ouyDDWuVJobcrAGZDoKRwO8eA

### Find existed gyms
GET  http://localhost:3334/api/workouts/gyms/16,17 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTExMTQyMCwiZXhwIjoxNjgxMTEyMzIwfQ.wMgsk-9HZPJ16yyODLS0FqUUGE2mXA0dscQFWBmc97Y

### Find existed coach's workouts
GET  http://localhost:3334/api/workouts/coach?limit=6&page=1&rating=2,5&costs=500,3000&calories=1000,5000 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDI0MDg0YjcxZGZjMzY2ODM3ZWMiLCJlbWFpbCI6Im1lQGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoiSGF3ayBDaGlwIiwiaWF0IjoxNjg0MzQxNjY2LCJleHAiOjE2ODQzNDI1NjZ9.Gf9mP-UBaPA169USpwETUHoB5-_mRXYf0FVnWi_bxPg

### Find coach's orders
GET  http://localhost:3334/api/workouts/coach-orders?sortField=amountWorkout&sortDirection=desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDI0MDg0YjcxZGZjMzY2ODM3ZWMiLCJlbWFpbCI6Im1lQGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoiSGF3ayBDaGlwIiwiaWF0IjoxNjgxMTQzNTY2LCJleHAiOjE2ODExNDQ0NjZ9.smPHn3Ny4karkB4WYEipC_BYfPj9AGXtJF7Cs1UsADw

### Create a new order workout
POST http://localhost:3334/api/workouts/orders HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTE0Njc2NSwiZXhwIjoxNjgxMTQ3NjY1fQ.qKEpJ3okHPcm9bkwiX6cRW9FV85ymVHN8VQxK1K3i-E

{
  "type": "тренировка",
  "workoutId": 5,
  "cost": 2000,
  "amountWorkout": 2,
  "payment": "visa"
}

### Create a new review workout
POST http://localhost:3334/api/workouts/reviews HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTczOTg2NiwiZXhwIjoxNjgxNzQwNzY2fQ.DBoJPXaBIV9Em_k9o0OSW5mwaRU9aiZYutAd7SzLLsM

{
  "workoutId": 7,
  "rating": 5,
  "text": "Eu tempor pariatur voluptate magna in proident mollit. Lorem cillum veniam reprehenderit dolore excepteur ad id."
}

### Find reviews workout
GET http://localhost:3334/api/workouts/reviews/7?limit=2&page=2&sortDirection=desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTc0MTA1NywiZXhwIjoxNjgxNzQxOTU3fQ.0WybjqabL34yq4CPMDy9NrP0-QxiUvszoqJxCq1bGSE
