### Create user
POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Chip Hawk",
  "email": "me7@gmail.com",
  "password": "123456",
  "sex": "мужской",
  "dateBirth": "1993-03-26",
  "role": "тренер",
  "location": "Спортивная",
  "about": "Sunt dolore ut dolore minim minim magna aute magna laborum ex pariatur enim enim amet."
}

### Login user
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "me@gmail.com",
  "password": "123456"
}

### Refresh access token
POST http://localhost:3333/api/auth/refresh-token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MTQ1OTkzNywiZXhwIjoxNjgyMDY0NzM3fQ.x0WymgaXCvWMGN6ZKaYsnTvFaiIi2nEWq21dG8OsVdU

### Logout user
POST http://localhost:3333/api/auth/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBlZjRlN2M2ODgxY2NmOTkxODFjMjUiLCJlbWFpbCI6Im1lMkBnbWFpbC5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwibmFtZSI6IkNoaXAgSGF3ayIsImlhdCI6MTY3ODgwMTk3MSwiZXhwIjoxNjc4ODAyODcxfQ.XIyIGLRQNgmtmJ9e21kSBDMupu6Cwxh1a6sBcP3P-ao

### Add coach info
PATCH http://localhost:3333/api/auth/additional-info/6412f62f52534cf32deec48c HTTP/1.1
Content-Type: application/json

{
  "experience": "профессионал",
  "specializations": ["кроссфит", "силовые"],
  "certificates": "test.pdf",
  "achievement": "Dolore duis ea nostrud consequat eu laborum excepteur labore adipisicing esse sit duis sit minim.",
  "isIndividualTraining": true
}

### Add customer info
PATCH http://localhost:3333/api/auth/additional-info/64120109f25c1ba058dd1e4c HTTP/1.1
Content-Type: application/json

{
  "experience": "любитель",
  "specializations": ["кроссфит", "аэробика"],
  "trainingTime": "10-30 мин",
  "targetDeclineСalories": 1000,
  "dayDeclineCalories": 1000,
  "isReadyTraining": false
}
