version: '3.5'
services:
  fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: "fitfriends.notify.fakesmtp"
    hostname: "fakesmtp"
    ports:
      - "5025:5025"
      - "8083:5080"

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: fitfriends.notify.rabbitmq
    ports:
      - '8084:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: test
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongodb:
    image: mongo
    restart: always
    container_name: fitfriends.notify.mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: fitfriends-notify
    ports:
      - 27018:27017
    volumes:
      - ./db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/fitfriends-notify --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: fitfriends.notify.mongo-express
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb:27017/

  redis-cache:
    image: redis:7.0.10-alpine
    container_name: fitfriends.notify.redis
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
