### Find user
GET http://localhost:3333/api/users/640b424084b71dfc366837ec HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDI0MDg0YjcxZGZjMzY2ODM3ZWMiLCJlbWFpbCI6Im1lQGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoiSGF3ayBDaGlwIiwiaWF0IjoxNjc5NDkxODIzLCJleHAiOjE2Nzk0OTI3MjN9.b9KLIRbhFdgS94c3cj0CzIC_81Deo4pr0shkJT7Fzg4

### Find users
GET http://localhost:3333/api/users?limit=5&page=1&sortDirection=asc&locations=Удельная,Звёздная&specializations=йога,бег,стрейчинг,силовые&experience=новичок&role=пользователь HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDI0MDg0YjcxZGZjMzY2ODM3ZWMiLCJlbWFpbCI6Im1lQGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoiSGF3ayBDaGlwIiwiaWF0IjoxNjc5NTAxNDA0LCJleHAiOjE2Nzk1MDIzMDR9.ZU7l67rpafdQzdpA-CZ7QM6VNy5AaUb9ADSGBjsc3zc

### Find user's friends
GET http://localhost:3333/api/users/my-friends HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MDg0MzEwMiwiZXhwIjoxNjgwODQ0MDAyfQ.A34SbK_vc8r3ZpUfQBkdAxCPtUAeaiyZ43AGsKcU744

### Add to user's friends
POST http://localhost:3333/api/users/my-friends/641200eef25c1ba058dd1e41 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MDg3MDI0MSwiZXhwIjoxNjgwODcxMTQxfQ.6e4GGEauY0T90Djz6F55f8PrzcIj4BCxkFhP6mtrdUs

### Delete user's friend
DELETE http://localhost:3333/api/users/my-friends/641200eef25c1ba058dd1e42 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY4MDg3MDI0MSwiZXhwIjoxNjgwODcxMTQxfQ.6e4GGEauY0T90Djz6F55f8PrzcIj4BCxkFhP6mtrdUs

### Update user profile
PATCH http://localhost:3333/api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDI0MDg0YjcxZGZjMzY2ODM3ZWMiLCJlbWFpbCI6Im1lQGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoiSGF3ayBDaGlwIiwiaWF0IjoxNjc5NDkxODIzLCJleHAiOjE2Nzk0OTI3MjN9.b9KLIRbhFdgS94c3cj0CzIC_81Deo4pr0shkJT7Fzg4

{
  "name": "Hawk Chip",
  "about": "Cupidatat ex nostrud sunt nostrud magna.",
  "experience": "профессионал",
  "specializations": ["йога", "бокс"],
  "certificates": "test.pdf",
  "achievement": "Dolore duis ea nostrud consequat eu laborum excepteur labore adipisicing esse sit duis sit minim.",
  "isIndividualTraining": true
}
