### Find user
GET http://localhost:3333/api/user/640b424084b71dfc366837ec HTTP/1.1

### Find users
GET http://localhost:3333/api/user?limit=5&page=1&sortDirection=asc&locations=Удельная,Звёздная&specializations=йога,бег,стрейчинг,силовые&experience=новичок&role=пользователь HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiNDJiYzg0YjcxZGZjMzY2ODM3ZjIiLCJlbWFpbCI6Im1lMUBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY3ODk2MTgxMSwiZXhwIjoxNjc4OTYyNzExfQ.lilm-cSUCiS8X73RFgIam6mukfDLF5CBOtem1v2IKZc

### Update user profile
PATCH http://localhost:3333/api/user/640b42bc84b71dfc366837f2 HTTP/1.1
Content-Type: application/json

{
  "name": "Hawk Chip",
  "about": "Cupidatat ex nostrud sunt nostrud magna.",
  "experience": "профессионал",
  "specializations": ["йога", "бокс"],
  "certificates": "test.pdf",
  "achievement": "Dolore duis ea nostrud consequat eu laborum excepteur labore adipisicing esse sit duis sit minim.",
  "isIndividualTraining": true
}
